name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - PreProduction
          - Production
      repo:
        description: Repository
        type: string
        required: true
      tag:
        description: Tag to rollback to
        type: string
        required: true
      rancherProjectID:
        description: Rancher project id
        type: string
        required: true
      rancherKey:
        description: Rancher key
        type: string
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: |
          chmod +x ./test.sh

      - name: Run rollback script
        run: ./test.sh "${{ github.event.inputs.environment }}" "${{ github.event.inputs.repo }}" "${{ github.event.inputs.tag }}" "${{ github.event.inputs.rancherProjectID }}" "${{ github.event.inputs.rancherKey }}"
